### ISSUE TITLE
Got error no selenium

### ISSUE THREAD

**Issue by zkenstein** [aidan846/Youtube-View-Bot#1]
Hello tried it, and got error `ModuleNotFoundError: No module named 'selenium'`

**Comment by aidan846** [comment]
Try this out. https://www.geeksforgeeks.org/how-to-install-selenium-in-python/ — I forgot to include a tutorial on how to install selenium. So my bad.

**Comment by zkenstein** [comment]
> Try this out. https://www.geeksforgeeks.org/how-to-install-selenium-in-python/ — I forgot to include a tutorial on how to install selenium. So my bad.

Nice, thanks mate
