### ISSUE TITLE
Cannot Run while path process

### ISSUE THREAD

**Issue by Aozgr** [aidan846/Youtube-View-Bot#5]
On Cmd, i cannot run bot.py Can you advise me how to do?

Thank you for helping,
Kind regards

![screenshot](https://github.com/user-attachments/assets/87c0bc17-df9e-4377-b3b8-37e6474ef528)

**Comment by aidan846** [comment]
I should have deleted or disabled this github, but this is extremely outdated and I am not working on it anymore, so I don't know if things will work or not.
